# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.1
      env:
        CC_TEST_REPORTER_ID: "4f212584f3b9fb97825fbcf9ecae951cb3b5de71b6ab502cf9feee7932a5babe"
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
        coverageCommand: mvn install
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
        debug: true

    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
          name: springboot-war-jar-keycloak-https
          token: ${{secrets.CC_REPORTER_ID}}
          file: ${{github.workspace}}/target/site/jacoco/jacoco.xml
          flags: unittests

