# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test & publish code coverage
      uses: Milfist/springboot-war-jar-keycloak-https
      env:
        # Set CC_TEST_REPORTER_ID as secret of your repo
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TOKEN}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
        # The report file must be there, otherwise Code Climate won't find it
        coverageCommand: mvn test
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco


